[package]
name = "b"
version = "0.1.0"
authors = ["Ron Ziroby Romero <ziroby@ziroby.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
